#include "../src/HATS/includes.hats"
staload _ = "../src/DATS/hashtbl_chain.dats"
staload _ = "libats/DATS/hashfun.dats"
staload _ = "../src/DATS/linmap_list.dats"
staload _ = "../src/DATS/hashtbl.dats"